<?php
/**
 * User: jeckel
 * Date: 21/04/19
 * Time: 15:45
 */

namespace Test\Jeckel\Gherkin;

use Codeception\Lib\ModuleContainer;
use Jeckel\Gherkin\Clock;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use org\bovigo\vfs\vfsStreamWrapper;
use PHPUnit\Framework\MockObject\MockObject;

class ClockTest extends \Codeception\Test\Unit
{
    /** @var Clock */
    protected $helper;

    public function setUp(): void
    {
        /** @var MockObject | ModuleContainer $moduleContainer */
        $moduleContainer = $this->createMock(ModuleContainer::class);

        $this->helper = new Clock($moduleContainer);

        vfsStreamWrapper::register();
        vfsStreamWrapper::setRoot(new vfsStreamDirectory('clockDir'));
        $this->helper->setProjectDir(vfsStream::url('clockDir'));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSetFakeClockTo(): void
    {
        $clock =  '2018-01-01 10:10:00';
        $clockFile = '/clock';

        $this->helper->_setConfig(['clock_path' => $clockFile]);

        $this->helper->setFakeClockTo($clock);
        $this->assertTrue(vfsStreamWrapper::getRoot()->hasChild('clock'));
        $this->assertEquals($clock, file_get_contents(vfsStream::url('clockDir') . $clockFile));
    }
}
